### ISSUE TITLE
issue on 92.0

### ISSUE THREAD

**Issue by pergolafabio** [aFrankLion/hass-google_keep#1]
hi, i am using this component already for a long time, but since today, upgraded to 92.0 , i receive now this error :(

2019-04-25 10:45:20 ERROR (MainThread) [homeassistant.setup] Error during setup of component google_keep
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/setup.py", line 156, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
AttributeError: module 'custom_components.google_keep' has no attribute 'setup'

**Comment by aFrankLion** [comment]
Looks like 0.92 had some extra requirements for custom components. Let me know know if the changes in [8e3238](https://github.com/aFrankLion/hass-google_keep/commit/88e3238b87c1ac64aa718e4f75ff2ce697199257) fixes your issue.

**Comment by pergolafabio** [comment]
Hi , thnx for the update, yes, I already fixed it by making those files, I just created empty ones....
But...

1) I need to copy paste them in the root folder of custom_components, not in its own directory like google_keep, is that normal? It is because google_keep isn't a platform of a domain like for example "sensor" ?

2) about gkeeapi, I also need to download gkeeapi from GitHub, and extract bit directly in my config folder, otherwise it doesn't work, also error filed then.. running hassio here on hassos, so I can't do the PiP command... Normally the gkeeapi should be installed in the dept fold by the requirement?

**Comment by pergolafabio** [comment]
Aha, now I see, for my issue 1, you don't have a google_keep.py file anymore, ok that's different, gonna try it later....
Just the gkeeapi, gonna remove it too, and let's see if it installs automatically

**Comment by aFrankLion** [comment]
Yes, with the recent changes, the requirements and dependencies are specified in the manifest.json file. Using the version in the repo should cause gkeepapi to be installed as previously.

I'm not running hassio, so I can't test this solution directly. Let me know if the current state of the repository installs correctly for you on with 0.92 on hassio before I close the issue. Thanks.

**Comment by pergolafabio** [comment]
Ok, Will try it out with new files...
But how do you normally install gkeeapi? If you can't use the pip command? Should it not install automatically with the requirement when loading the .py file?

**Comment by pergolafabio** [comment]
ok, up and running, deleted gkpeeapi from my config / deps folder, rebooted hassio, then installed those 3 new files in a google_keep directory
it installed fine, even now gkeepapi installed fine

but i receive this error now, when adding items, think something wrong with the service:

json was in error below as test : 

{"list_name":"colruyt","items":"test1"}

also my ifttt applet that i didnt touch does give an error now


2019-04-26 15:43:04 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.139757369701992] extra keys not allowed @ data['list_name']
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 121, in handle_call_service
    connection.context(msg))
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1118, in async_call
    processed_data = handler.schema(service_data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 267, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 589, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 427, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['list_name']

**Comment by pergolafabio** [comment]
in servces.yaml i renamed list_name to title like below, then if i call a service from HA itself, it works
but my IFTTT doesnt work anymore

as soon as i say "add something to the shoplist" i recieve now an error from google : 

there went something wrong
dont see anything in the log, so not sure its IFTTT related

**Comment by pergolafabio** [comment]
in IFTTT body i have : 

{ "action": "call_service", "service": "google_keep.add_to_list", "title":"Colruyt", "shop":" {{TextField}}" }

in my automation i have : 

```
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: call_service
  action:
    service_template: '{{ trigger.event.data.service }}'
    data_template:
      title: '{{ trigger.event.data.title }}'  
      items: '{{ trigger.event.data.shop }}'   
```

i renamed "items" to "shop" , cause before  "trigger.event.data.items" did not work properly , but this worked before : "trigger.event.data.shop"

**Comment by pergolafabio** [comment]
ok, disregared, my IFTTT issue, its working again, seems i was logged out on my android phone, it works now

but the only issue left is i think your services.yaml file, i needed to change "list_name" to "title"

**Comment by aFrankLion** [comment]
Thanks for all the information! I'm going to do a clean re-install of the custom component on my machine and make sure I have consistent keywords in all the files and readme examples. As you suggested, "items" may be a protected name, and switching to something may solve the issue.

**Comment by pergolafabio** [comment]
Ok, thnx

**Comment by pergolafabio** [comment]
Btw , you gonna make this an official component?

**Comment by aFrankLion** [comment]
Months ago, I heard a rumor that Google Keep integration was returning to Google Home. After that, I assumed this workaround would become mostly unnecessary, and I stopped adding features to this component.

That was a while ago, however. I'll have to read up on the requirements to get this integrated, as I think it does serve a useful purpose.

**Comment by pergolafabio** [comment]
Yes, I am following that rumour too , that was almost a year ago ;)
My problem is that IFTTT still doesn't excists in our native language :(
