### ISSUE TITLE
Google Keep sign-in error

### ISSUE THREAD

**Issue by ghost** [aFrankLion/hass-google_keep#15]
Since today the integration Google seems to require a browser login.
The following error message is in the logs and the integration doesn't work any more.

```
Logger: homeassistant.setup
Source: custom_components/google_keep/__init__.py:71
Integration: Google Keep (documentation)
First occurred: 19:39:03 (1 occurrences)
Last logged: 19:39:03

Error during setup of component google_keep
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/google_keep/__init__.py", line 71, in setup
    login_success = keep.login(username, password)
  File "/usr/local/lib/python3.9/site-packages/gkeepapi/__init__.py", line 695, in login
    ret = auth.login(username, password, device_id)
  File "/usr/local/lib/python3.9/site-packages/gkeepapi/__init__.py", line 59, in login
    raise exception.LoginException(
gkeepapi.exception.LoginException: ('NeedsBrowser', 'To access your account, you must sign in on the web. Touch Next to start browser sign-in.')
```

**Comment by alkcxy** [comment]
You need to create an api key on the google account and use it to sign up instead of your password

**Comment by ghost** [comment]
How can an API key be used with this integration? The documentation just states app-passwords for login, which are phased out by Google.

**Comment by alkcxy** [comment]
in your google account search for the section "password for apps" or something similar (in italian is "password per le app", unfortunately, I'm not able to localize the page in English).
There you can create a specific password.
Then in the configuration.yaml of you ha instance, you can put

```
google_keep:
  username: youremail@gmail.com
  password: your-password-for-app
```

**Comment by ghost** [comment]
I have used such an app password. But it stopped working and requiring a web login in the log as seen above. Google published that the app passwords are going to be phased out and a web login will be mandatory.
https://support.google.com/accounts/answer/6010255?hl=en

**Comment by alkcxy** [comment]
you're right, Google has deprecated the use of your own password for accessing third-party apps.
In fact you must create a specific password for a third-party app, as I have already told you in the previous comment ;) 

Please scroll down that page and read carefully the section ["Use an App-Password"](https://support.google.com/accounts/answer/6010255#zippy=%2Cuse-an-app-password)

**Comment by ghost** [comment]
I have done that. I have even created a new app specific password. Does not work anymore.

**Comment by alkcxy** [comment]
I can't replicate your issue and the app-password is the correct way as already stated by Google and shouldn't ask you for a web login. In fact I am using it.

**Comment by alkcxy** [comment]
I was finally able to replicate your error and unfortunately, we should move to the "sign in with Google" form but right now I don't have time for this change

**Comment by ghost** [comment]
With HA 2022.06.0 this integration works again (on two independant instances). Maybe the new store mechanism for the OAuth credentials of the Google calendar  integration fixed it (kind of - if you use the Google calendar integration).

**Comment by alkcxy** [comment]
Umh, strange enough it's working again even without the google calendar integration! (tested on an instance that is not using that integration yet)
