### ISSUE TITLE
ifttt new webhook, keyword "items" giving an empty shopitem

### ISSUE THREAD

**Issue by pergolafabio** [aFrankLion/hass-google_keep#2]
because API is deprecated, i started to use the new IFTTT component and webhooks

so created an automation, but if you use the data template / body like this : 

```
body : { "action": "call_service", "service": "google_keep.add_to_list", "title":"shoplist", "items":" {{TextField}}" }

    data_template:
      title: '{{ trigger.event.data.title }}'  
      items: '{{ trigger.event.data.items }}'  
```

then it creates an empty item
seems the keyword "items" cant be use here , i think its an internal keyword in this sentence: trigger.event.data.items

so i renamed it to for example:

```
body : { "action": "call_service", "service": "google_keep.add_to_list", "title":"shoplist", "shop_item":" {{TextField}}" }

    data_template:
      title: '{{ trigger.event.data.title }}'  
      items: '{{ trigger.event.data.shop_item }}'  
```

then it does work :)

maybe the readme needs an update?

**Comment by aFrankLion** [comment]
Confirmed. With homeassistant 0.91.3, I was getting <built-in method items of dict object at ...> added to my grocery list when using the name "items" for the things to add to the Keep list with the formatting you use. I'll make the appropriate updates to the readme, as my IFTTT instructions are out of date.

**Comment by pergolafabio** [comment]
;)

Yeah API is not used anymore, webhook is safer to use...

But normally Google keep would be coming back native to Google assistant anyway, as a list and notes Integration.... So don't put too much work in it ;)

**Comment by aFrankLion** [comment]
Updated the readme, but also refactored "item" and "items" out of the component, replacing them with "thing" and "things". "item" was a poor choice for Python.

**Comment by pergolafabio** [comment]
Ty ;)
