### ISSUE TITLE
Add Version key in manifest file

### ISSUE THREAD

**Issue by jokerigno** [aFrankLion/hass-google_keep#8]
Hi,

I found a warning message in logs. I'm quite sure that you already know it but if don't please have a look at it:

No 'version' key in the manifest file for custom integration 'google_keep'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'media_player_template'

**Comment by aFrankLion** [comment]
Thanks for the heads up! I hadn't seen this requirement yet.

**Comment by jokerigno** [comment]
One is glad to be of service 😀
