### ISSUE TITLE
Sync a google keep list with the hass shopping list integration

### ISSUE THREAD

**Issue by alkcxy** [aFrankLion/hass-google_keep#9]
I worked on a fork of this project to add a new service for syncing a google keep list into the shopping list integration. 
Basically, it adds into the shopping list integration only the items unchecked in the google keep list and updates the items that exist in both the lists but have a different value on the checked attribute. Currently, the flow is from google keep to the shopping list but I was also thinking of a service that works backwards.
If you're interested, I could create a PR.

**Comment by pergolafabio** [comment]
Is it possible to use the HA native in google assistant? I can't use the keep list, since it's only available for English language

**Comment by pergolafabio** [comment]
Or is there a way to integrate it to google assistant without IFTTT? With an official domain?

**Comment by alkcxy** [comment]
Unfortunately for what I know, It's not possible to use the HA shopping list through Google Assistant in fact, I use google keep as a shopping list, and in this way, I can tell in Italian to google assistant to add something to my shopping list. With the unofficial google keep library, I can then sync the google keep list with the shopping list and the changes that I push to my fork are all about this. I'm also realizing that instead of a service should also be possible to create an entity that can mirror the google keep list into HA.

**Comment by pergolafabio** [comment]
You are taking about the "list and notes" integration? That's still not supported in dutch language :-( , so I am looking for an alternative

**Comment by alkcxy** [comment]
I'm talking about this integration: https://www.home-assistant.io/integrations/shopping_list/ 
Italian language is not supported too for the voice command part but is fully translated on the UI.
If you then configure a list of google keep as the main shopping list on google assistant you should be able to tell Google to add a certain item to your shopping list in your language and it will use this google keep list for this operation.

With the service that I added, you can have it synced into the shopping list home assistant integration

**Comment by pergolafabio** [comment]
yeah, but thats the problem, i cant choose "google keep" as provider in my google assistant, there are no providers for my language

**Comment by aFrankLion** [comment]
> 
> 
> I worked on a fork of this project to add a new service for syncing a google keep list into the shopping list integration.
> Basically, it adds into the shopping list integration only the items unchecked in the google keep list and updates the items that exist in both the lists but have a different value on the checked attribute. Currently, the flow is from google keep to the shopping list but I was also thinking of a service that works backwards.
> If you're interested, I could create a PR.

@alkcxy, Please do create a PR. I think this is a great addition.

**Comment by alkcxy** [comment]
Thanks @aFrankLion. I think we need to do some rework on it or rethink if it could be better to create an entity but in the meanwhile I created a draft Pr #10

**Comment by alkcxy** [comment]
> yeah, but thats the problem, i cant choose "google keep" as provider in my google assistant, there are no providers for my language

Sorry for your problem, in that case only Google can solve your problem, I fear. Or you should try some other solution that can be integrated in both GA and HA in Dutch language.

**Comment by aFrankLion** [comment]
Closed with pull request #10
